---
title: C28198
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
ms.openlocfilehash: 10236f359bff722c0b63bb0e9db7a7f38d41b7e8
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/17/2020
ms.locfileid: "77417608"
---
# <a name="c28198"></a>C28198

> aviso C28198: possivelmente vazando memória devido a uma exceção.

Esse aviso indica que a memória alocada não está sendo liberada depois que uma exceção é gerada. A instrução no final do caminho pode gerar uma exceção. A memória foi passada para uma função que pode ter salvo uma cópia para ser liberada posteriormente.

Esse aviso é muito semelhante ao [C28197](../code-quality/c28197.md)de aviso. As anotações recomendadas para uso com [C28197](../code-quality/c28197.md) de aviso também podem ser usadas aqui.

## <a name="example"></a>Exemplo

O exemplo de código a seguir gera este aviso:

```cpp
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

O exemplo de código a seguir evita esse aviso:

```cpp
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```
