---
title: C6255
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
ms.openlocfilehash: 646147960e5502390f513fa027b825ca7193d335
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 09/29/2020
ms.locfileid: "91498970"
---
# <a name="c6255"></a>C6255

> aviso C6255: _alloca indica falha ao gerar uma exceção de estouro de pilha. Considere usar _malloca em vez disso

Esse aviso indica que uma chamada para `_alloca` foi detectada fora do tratamento de exceção local. `_alloca` deve ser sempre chamado de dentro do intervalo protegido de um manipulador de exceção, pois ele pode gerar uma exceção de estouro de pilha em caso de falha. Se possível, em vez de usar `_alloca` , considere usar `_malloca` o que é uma versão mais segura do `_alloca` .

## <a name="example"></a>Exemplo

O código a seguir gera este aviso porque `_alloca` pode gerar exceção:

```cpp
#include <windows.h>

void f( )
{
  void *p = _alloca(10);
  // code ...
}
```

Para corrigir esse aviso, use `_malloca` e adicione o manipulador de exceção, conforme mostrado no código a seguir:

```cpp
#include <windows.h>
#include <malloc.h>

void f( )
{
  void *p;
  int errcode;
  __try
  {
    p = _malloca(10);
    // code...
    _freea(p);
  }
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    errcode = _resetstkoflw();
    // code ...
  }
}
```

## <a name="see-also"></a>Consulte também

[_malloca](../c-runtime-library/reference/malloca.md)
