---
title: C6255
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
ms.openlocfilehash: f38d45d8e252261acfc09de389a44f4ba85650e9
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/17/2020
ms.locfileid: "77420436"
---
# <a name="c6255"></a>C6255

> aviso C6255: _alloca indica falha ao gerar uma exceção de estouro de pilha. Considere usar _malloca em vez disso

Esse aviso indica que uma chamada para `_alloca` foi detectada fora do tratamento de exceção local. `_alloca` sempre deve ser chamado de dentro do intervalo protegido de um manipulador de exceção, pois ele pode gerar uma exceção de estouro de pilha em caso de falha. Se possível, em vez de usar `_alloca`, considere o uso de `_malloca` que é uma versão mais segura do `_alloca`.

## <a name="example"></a>Exemplo

O código a seguir gera esse aviso porque `_alloca` pode gerar a exceção:

```cpp
#include <windows.h>

void f( )
{
  void *p = _alloca(10);
  // code ...
}
```

Para corrigir esse aviso, use `_malloca` e adicione o manipulador de exceção, conforme mostrado no código a seguir:

```cpp
#include <windows.h>
#include <malloc.h>

void f( )
{
  void *p;
  int errcode;
  __try
  {
    p = _malloca(10);
    // code...
    _freea(p);
  }
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    errcode = _resetstkoflw();
    // code ...
  }
}
```

## <a name="see-also"></a>Confira também

[_malloca](/cpp/c-runtime-library/reference/malloca)
